/** @format */

import Head from "next/head";
import useFirebase from "../hooks/useFirebase";
import Hero from "../views/pages/Home/Hero/Hero";
import Layout from "../views/shared/Layout/Layout";

export const Home = () => {
    const { user, signinWith0Handler } = useFirebase();

    console.log("Email: ", user?.email);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout className={"mv_page-home"}>
                <Hero /> {/* Hero Section */}
            </Layout>
        </>
    );
};

export default Home;
